import 'package:FitStart/model/gym.dart';
import 'package:FitStart/model/gym_amenity.dart';
import 'package:FitStart/model/gym_membership.dart';

// Gym Amenities
var _weights =
    GymAmenity(name: "Free Weights", imageAsset: "assets/icons/weights.png");
var _cardio =
    GymAmenity(name: "Cardio Zone", imageAsset: "assets/icons/cardio.png");
var _yoga =
    GymAmenity(name: "Yoga Studio", imageAsset: "assets/icons/yoga.png");
var _sauna = GymAmenity(name: "Sauna", imageAsset: "assets/icons/sauna.png");
var _steamRoom =
    GymAmenity(name: "Steam Room", imageAsset: "assets/icons/steam.png");
var _swimming =
    GymAmenity(name: "Swimming Pool", imageAsset: "assets/icons/swimming.png");
var _crossfit =
    GymAmenity(name: "CrossFit Area", imageAsset: "assets/icons/crossfit.png");
var _functional = GymAmenity(
    name: "Functional Training", imageAsset: "assets/icons/functional.png");
var _boxing =
    GymAmenity(name: "Boxing Ring", imageAsset: "assets/icons/boxing.png");
var _spinning =
    GymAmenity(name: "Spin Studio", imageAsset: "assets/icons/spinning.png");
var _parking =
    GymAmenity(name: "Parking", imageAsset: "assets/icons/parking.png");
var _showers =
    GymAmenity(name: "Showers", imageAsset: "assets/icons/shower.png");
var _lockers =
    GymAmenity(name: "Lockers", imageAsset: "assets/icons/lockers.png");
var _wifi = GymAmenity(name: "WiFi", imageAsset: "assets/icons/wifi.png");
var _cafe =
    GymAmenity(name: "Protein Cafe", imageAsset: "assets/icons/canteen.png");
var _ac =
    GymAmenity(name: "Air Conditioned", imageAsset: "assets/icons/ac.png");

// Mumbai Gyms
List<Gym> gymList = [
  Gym(
    id: "GYM01",
    name: "Gold's Gym Bandra",
    type: "Mixed",
    address: "Linking Road, Bandra West, Mumbai",
    phoneNumber: "+91 98765 11111",
    openDay: "Monday to Sunday",
    openTime: "05.00",
    closeTime: "23.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 3500,
    dailyPrice: 200,
    latitude: 19.0596,
    longitude: 72.8295,
    rating: 4.8,
    author: "Victor Freitas",
    authorUrl: "https://unsplash.com/@victorfreitas",
    imageUrl:
        "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 800,
    amenities: [
      _weights,
      _cardio,
      _functional,
      _sauna,
      _showers,
      _parking,
      _wifi,
      _lockers
    ],
    description:
        "Premium gym with state-of-the-art equipment and certified trainers.",
  ),
  Gym(
    id: "GYM02",
    name: "Talwalkars Gym Andheri",
    type: "Bodybuilding",
    address: "Andheri East, Mumbai",
    phoneNumber: "+91 98765 22222",
    openDay: "Monday to Sunday",
    openTime: "06.00",
    closeTime: "22.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 3000,
    dailyPrice: 180,
    latitude: 19.1136,
    longitude: 72.8697,
    rating: 4.6,
    author: "Danielle Cerullo",
    authorUrl: "https://unsplash.com/@dncerullo",
    imageUrl:
        "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: false,
    trainerPrice: 700,
    amenities: [_weights, _cardio, _showers, _parking, _lockers, _wifi],
    description: "Focus on strength training and bodybuilding programs.",
  ),
  Gym(
    id: "GYM03",
    name: "Fitness First Powai",
    type: "Mixed",
    address: "Hiranandani, Powai, Mumbai",
    phoneNumber: "+91 98765 33333",
    openDay: "All Days",
    openTime: "05.00",
    closeTime: "23.30",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 4000,
    dailyPrice: 250,
    latitude: 19.1197,
    longitude: 72.9066,
    rating: 4.7,
    author: "Sven Mieke",
    authorUrl: "https://unsplash.com/@sxoxm",
    imageUrl:
        "https://images.unsplash.com/photo-1540497077202-7c8a3999166f?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 900,
    amenities: [
      _weights,
      _cardio,
      _functional,
      _swimming,
      _sauna,
      _steamRoom,
      _yoga,
      _spinning,
      _parking,
      _showers,
      _wifi,
      _cafe,
      _lockers
    ],
    description: "Luxury fitness center with swimming pool and spa facilities.",
  ),
  Gym(
    id: "GYM04",
    name: "Cult.fit Gym Malad",
    type: "Functional",
    address: "Malad West, Mumbai",
    phoneNumber: "+91 98765 44444",
    openDay: "Monday to Sunday",
    openTime: "06.00",
    closeTime: "22.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 2500,
    dailyPrice: 150,
    latitude: 19.1866,
    longitude: 72.8356,
    rating: 4.5,
    author: "Risen Wang",
    authorUrl: "https://unsplash.com/@risen_wang",
    imageUrl:
        "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 600,
    amenities: [_functional, _cardio, _yoga, _showers, _parking, _wifi],
    description: "Modern functional training with group workout sessions.",
  ),
  Gym(
    id: "GYM05",
    name: "The Gym Juhu",
    type: "Mixed",
    address: "Juhu Tara Road, Mumbai",
    phoneNumber: "+91 98765 55555",
    openDay: "All Days",
    openTime: "05.30",
    closeTime: "23.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 3800,
    dailyPrice: 220,
    latitude: 19.0990,
    longitude: 72.8266,
    rating: 4.9,
    author: "Anastase Maragos",
    authorUrl: "https://unsplash.com/@visualsbyroyalz",
    imageUrl:
        "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 850,
    amenities: [
      _weights,
      _cardio,
      _crossfit,
      _functional,
      _sauna,
      _showers,
      _parking,
      _wifi,
      _cafe,
      _lockers
    ],
    description: "Elite gym with celebrity trainers and premium equipment.",
  ),

  // Bangalore Gyms
  Gym(
    id: "GYM06",
    name: "Snap Fitness Indiranagar",
    type: "Mixed",
    address: "100 Feet Road, Indiranagar, Bangalore",
    phoneNumber: "+91 98765 66666",
    openDay: "Open 24/7",
    openTime: "00.00",
    closeTime: "23.59",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 3200,
    dailyPrice: 190,
    latitude: 12.9716,
    longitude: 77.6412,
    rating: 4.6,
    author: "Sam Sabourin",
    authorUrl: "https://unsplash.com/@samsabourin",
    imageUrl:
        "https://images.unsplash.com/photo-1576678927484-cc907957088c?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: false,
    trainerPrice: 750,
    amenities: [_weights, _cardio, _functional, _showers, _parking, _wifi, _ac],
    description: "24/7 fitness center with flexible workout hours.",
  ),
  Gym(
    id: "GYM07",
    name: "Anytime Fitness Koramangala",
    type: "Mixed",
    address: "5th Block, Koramangala, Bangalore",
    phoneNumber: "+91 98765 77777",
    openDay: "Open 24/7",
    openTime: "00.00",
    closeTime: "23.59",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 3500,
    dailyPrice: 210,
    latitude: 12.9352,
    longitude: 77.6245,
    rating: 4.7,
    author: "Humphrey Muleba",
    authorUrl: "https://unsplash.com/@good_citizen",
    imageUrl:
        "https://images.unsplash.com/photo-1574680096145-d05b474e2155?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 800,
    amenities: [
      _weights,
      _cardio,
      _functional,
      _spinning,
      _showers,
      _parking,
      _wifi,
      _lockers
    ],
    description: "Round-the-clock access with modern fitness equipment.",
  ),
  Gym(
    id: "GYM08",
    name: "Sculpt Gym Whitefield",
    type: "Bodybuilding",
    address: "ITPL Main Road, Whitefield, Bangalore",
    phoneNumber: "+91 98765 88888",
    openDay: "Monday to Saturday",
    openTime: "06.00",
    closeTime: "22.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 2800,
    dailyPrice: 170,
    latitude: 12.9698,
    longitude: 77.7499,
    rating: 4.5,
    author: "Alora Griffiths",
    authorUrl: "https://unsplash.com/@aloragriffiths",
    imageUrl:
        "https://images.unsplash.com/photo-1584466977773-e625c37cdd50?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: false,
    trainerPrice: 650,
    amenities: [_weights, _cardio, _showers, _parking, _lockers, _wifi],
    description: "Specialized in bodybuilding and strength training.",
  ),
  Gym(
    id: "GYM09",
    name: "Yoga Studios HSR Layout",
    type: "Yoga",
    address: "Sector 2, HSR Layout, Bangalore",
    phoneNumber: "+91 98765 99999",
    openDay: "Monday to Sunday",
    openTime: "06.00",
    closeTime: "21.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 2000,
    dailyPrice: 120,
    latitude: 12.9121,
    longitude: 77.6446,
    rating: 4.8,
    author: "Jared Rice",
    authorUrl: "https://unsplash.com/@jareddrice",
    imageUrl:
        "https://images.unsplash.com/photo-1599901860904-17e6ed7083a0?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 500,
    amenities: [_yoga, _showers, _parking, _wifi, _lockers],
    description:
        "Dedicated yoga and meditation center with expert instructors.",
  ),
  Gym(
    id: "GYM10",
    name: "CrossFit Box Marathahalli",
    type: "CrossFit",
    address: "Marathahalli, Bangalore",
    phoneNumber: "+91 98765 10101",
    openDay: "Monday to Sunday",
    openTime: "05.30",
    closeTime: "22.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 4500,
    dailyPrice: 280,
    latitude: 12.9591,
    longitude: 77.6974,
    rating: 4.9,
    author: "Karsten Winegeart",
    authorUrl: "https://unsplash.com/@karsten116",
    imageUrl:
        "https://images.unsplash.com/photo-1517963879433-6ad2b056d712?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 1000,
    amenities: [_crossfit, _functional, _weights, _showers, _parking, _wifi],
    description:
        "Intense CrossFit training with certified coaches and group WODs.",
  ),

  // Delhi NCR Gyms
  Gym(
    id: "GYM11",
    name: "Fitness First Gurgaon",
    type: "Mixed",
    address: "DLF Phase 3, Gurgaon",
    phoneNumber: "+91 98765 10111",
    openDay: "All Days",
    openTime: "05.00",
    closeTime: "23.30",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 4200,
    dailyPrice: 260,
    latitude: 28.4983,
    longitude: 77.0909,
    rating: 4.7,
    author: "Jonathan Borba",
    authorUrl: "https://unsplash.com/@jonathanborba",
    imageUrl:
        "https://images.unsplash.com/photo-1605296867424-35fc25c9212a?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 900,
    amenities: [
      _weights,
      _cardio,
      _swimming,
      _sauna,
      _steamRoom,
      _yoga,
      _spinning,
      _showers,
      _parking,
      _wifi,
      _cafe
    ],
    description: "Premium fitness club with comprehensive facilities.",
  ),
  Gym(
    id: "GYM12",
    name: "Gold's Gym Connaught Place",
    type: "Bodybuilding",
    address: "Connaught Place, New Delhi",
    phoneNumber: "+91 98765 10112",
    openDay: "Monday to Sunday",
    openTime: "05.30",
    closeTime: "22.30",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 3800,
    dailyPrice: 230,
    latitude: 28.6304,
    longitude: 77.2177,
    rating: 4.8,
    author: "Jelmer Assink",
    authorUrl: "https://unsplash.com/@jelmerassink",
    imageUrl:
        "https://images.unsplash.com/photo-1593079831268-3381b0db4a77?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 850,
    amenities: [
      _weights,
      _cardio,
      _functional,
      _sauna,
      _showers,
      _parking,
      _wifi,
      _lockers
    ],
    description: "Iconic gym chain with professional bodybuilding focus.",
  ),
  Gym(
    id: "GYM13",
    name: "Cult.fit Sector 18 Noida",
    type: "Functional",
    address: "Sector 18, Noida",
    phoneNumber: "+91 98765 10113",
    openDay: "Monday to Sunday",
    openTime: "06.00",
    closeTime: "22.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 2600,
    dailyPrice: 160,
    latitude: 28.5685,
    longitude: 77.3246,
    rating: 4.5,
    author: "Meghan Holmes",
    authorUrl: "https://unsplash.com/@yellowteapot",
    imageUrl:
        "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 600,
    amenities: [_functional, _cardio, _yoga, _showers, _parking, _wifi],
    description: "Tech-enabled fitness with gamified workout sessions.",
  ),
  Gym(
    id: "GYM14",
    name: "Fight Club Saket",
    type: "Mixed",
    address: "Saket, South Delhi",
    phoneNumber: "+91 98765 10114",
    openDay: "Monday to Saturday",
    openTime: "06.00",
    closeTime: "22.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 3500,
    dailyPrice: 210,
    latitude: 28.5244,
    longitude: 77.2066,
    rating: 4.6,
    author: "Nigel Msipa",
    authorUrl: "https://unsplash.com/@nigelmsipa",
    imageUrl:
        "https://images.unsplash.com/photo-1571902943202-507ec2618e8f?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 750,
    amenities: [
      _boxing,
      _weights,
      _cardio,
      _functional,
      _showers,
      _parking,
      _wifi
    ],
    description: "Combat sports and MMA training with fitness programs.",
  ),
  Gym(
    id: "GYM15",
    name: "Equilibrium Gym Dwarka",
    type: "Mixed",
    address: "Sector 12, Dwarka, New Delhi",
    phoneNumber: "+91 98765 10115",
    openDay: "All Days",
    openTime: "05.30",
    closeTime: "23.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 3000,
    dailyPrice: 180,
    latitude: 28.5921,
    longitude: 77.0460,
    rating: 4.7,
    author: "Hayley Kim Design",
    authorUrl: "https://unsplash.com/@haylee_design",
    imageUrl:
        "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 700,
    amenities: [
      _weights,
      _cardio,
      _functional,
      _spinning,
      _showers,
      _parking,
      _wifi,
      _lockers
    ],
    description: "Well-balanced fitness center with diverse training options.",
  ),

  // Manipur Gyms
  Gym(
    id: "GYM16",
    name: "Fit Zone Imphal",
    type: "Mixed",
    address: "Thangal Bazar, Imphal, Manipur",
    phoneNumber: "+91 98765 20001",
    openDay: "Monday to Sunday",
    openTime: "05.30",
    closeTime: "21.30",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 1800,
    dailyPrice: 100,
    latitude: 24.8170,
    longitude: 93.9368,
    rating: 4.4,
    author: "John Arano",
    authorUrl: "https://unsplash.com/@johnarano",
    imageUrl: "https://images.unsplash.com/photo-1558017487-06bf9f82613a?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: false,
    trainerPrice: 500,
    amenities: [_weights, _cardio, _showers, _parking, _lockers],
    description: "Local favorite with friendly atmosphere and good equipment.",
  ),
  Gym(
    id: "GYM17",
    name: "Iron Paradise Gym",
    type: "Bodybuilding",
    address: "Paona Bazar, Imphal, Manipur",
    phoneNumber: "+91 98765 20002",
    openDay: "Monday to Saturday",
    openTime: "06.00",
    closeTime: "21.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 1500,
    dailyPrice: 90,
    latitude: 24.8079,
    longitude: 93.9442,
    rating: 4.3,
    author: "Alonso Reyes",
    authorUrl: "https://unsplash.com/@alonsoreyes",
    imageUrl:
        "https://images.unsplash.com/photo-1605296867304-46d5465a13f1?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: false,
    trainerPrice: 400,
    amenities: [_weights, _cardio, _showers, _lockers],
    description: "Hardcore bodybuilding gym with competitive atmosphere.",
  ),
  Gym(
    id: "GYM18",
    name: "CrossFit Manipur",
    type: "CrossFit",
    address: "Lamphelpat, Imphal, Manipur",
    phoneNumber: "+91 98765 20003",
    openDay: "Monday to Sunday",
    openTime: "05.30",
    closeTime: "21.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 2500,
    dailyPrice: 150,
    latitude: 24.7833,
    longitude: 93.9333,
    rating: 4.6,
    author: "Leon Ardho",
    authorUrl: "https://unsplash.com/@leonardho",
    imageUrl:
        "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 600,
    amenities: [_crossfit, _functional, _showers, _parking, _wifi],
    description: "First CrossFit affiliate in Manipur with certified coaches.",
  ),
  Gym(
    id: "GYM19",
    name: "Yoga Wellness Center",
    type: "Yoga",
    address: "Uripok, Imphal, Manipur",
    phoneNumber: "+91 98765 20004",
    openDay: "Monday to Sunday",
    openTime: "06.00",
    closeTime: "20.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 1200,
    dailyPrice: 80,
    latitude: 24.8013,
    longitude: 93.9511,
    rating: 4.7,
    author: "Anupam Mahapatra",
    authorUrl: "https://unsplash.com/@anupam_mahapatra",
    imageUrl: "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=500",
    hasPersonalTrainer: true,
    hasGroupClasses: true,
    trainerPrice: 350,
    amenities: [_yoga, _showers, _parking],
    description:
        "Traditional yoga and wellness center with meditation classes.",
  ),
  Gym(
    id: "GYM20",
    name: "Power Gym Thoubal",
    type: "Mixed",
    address: "Thoubal, Manipur",
    phoneNumber: "+91 98765 20005",
    openDay: "Monday to Saturday",
    openTime: "06.00",
    closeTime: "21.00",
    imageAsset: "assets/images/gym1.jpg",
    monthlyPrice: 1400,
    dailyPrice: 85,
    latitude: 24.6333,
    longitude: 93.9992,
    rating: 4.2,
    author: "Sergio Pedemonte",
    authorUrl: "https://unsplash.com/@sergio_pedemonte",
    imageUrl:
        "https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?w=500",
    hasPersonalTrainer: false,
    hasGroupClasses: false,
    trainerPrice: 0,
    amenities: [_weights, _cardio, _showers],
    description: "Budget-friendly gym with basic equipment and friendly staff.",
  ),
];

// Sample memberships (for demonstration)
List<GymMembership> dummyMemberships = [];
